apiVersion: apps/v1
kind: Deployment
metadata:
  name: placila-deployment
  labels:
    app: placila
spec:
  replicas: 3
  selector:
    matchLabels:
      app: placila
  template:
    metadata:
      labels:
        app: placila
    spec:
      containers:
        - image: tp7220/placila:latest
          name: placila
          env:
            - name: DATABASE_IP
              value: "postgres-uporabniki"
            - name: DATABASE_PORT
              value: "5432"
            - name: PGDATABASE
              value: "paketiorg"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "postgres"
            - name: FLUENT_IP
              value: "TODO"
            - name: FLUENT_PORT
              value: "1000"
            - name: GRPC_SERVER_IP
              value: "grpcstreznik-service"
            - name: GRPC_SERVER_PORT
              value: "31000"

--- 

apiVersion: v1
kind: Service
metadata:
  name: placila-service
spec:
  type: NodePort
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 5002
  selector:
    app: placila